### ISSUE TITLE
The app doesn't work after a fresh install

### ISSUE THREAD

**Issue by Tagadda** [YunoHost-Apps/excalidraw_ynh#3]
### Describe the bug

After the installation, when you browse the app, the page displays "Loading scenes..." and nothing else ~~matters~~ happens.

![image](https://user-images.githubusercontent.com/36127788/169281252-8fb14d5b-d58e-4c0c-ac39-2b8cfad96c18.png)

### Context

- Hardware: VPS bought online
- YunoHost version:  4.3.6.3
- App Version : 0.11.0~ynh1
- I have access to my server: Through SSH, through the webadmin

### Steps to reproduce

- Install the app
- Try to access https://domain.tld/excalidraw

### Expected behavior

The app should load.

### Logs

[Install logs](https://paste.yunohost.org/raw/obejecarev)

**Comment by mdic** [comment]
same setup, same problem here; I've tried fiddling with the server, and noticed that - from the browser console - .js file that should reside in DOMAIN.LTD/static/js/*.js are not present - the folder "static" does not exist in the excalidraw www folder - and they redirect to YNH SSO.

**Comment by CodeFreezr** [comment]
Same Problem here. Anybody able to fix this?

**Comment by CodeFreezr** [comment]
Ok. Sounds there is a solution somewhere. Great! But how can I get it on my Ynh-Server? Should i simply wait for QA'ing, should I do something in my self for this? Sorry, totaly new in YNH^^

**Comment by mdic** [comment]
many thanks @yalh76 for all the work; I have tried installing the `example` branch on my ynh (from scratch, without upgrading an existing `master` installation) using the command below but unfortunately the same issue faces up.

`sudo yunohost app install https://github.com/YunoHost-Apps/excalidraw_ynh/tree/example --debug`

It is highly likely I have made mistakes along the way; any suggestions? Thanks in advance!

**Comment by CodeFreezr** [comment]
I'm really impressed with the depth and scope of the testing, as seen in [PR-4](https://github.com/YunoHost-Apps/excalidraw_ynh/pull/4), but now how do we get this done?

**Comment by CodeFreezr** [comment]
> many thanks @yalh76 for all the work; I have tried installing the `example` branch on my ynh (from scratch, without upgrading an existing `master` installation) using the command below but unfortunately the same issue faces up.
> 
> `sudo yunohost app install https://github.com/YunoHost-Apps/excalidraw_ynh/tree/example --debug`
> 
> It is highly likely I have made mistakes along the way; any suggestions? Thanks in advance!

At the moment it's just Version 0.11.0~ynh1 which brakes. If PR-4 would be ready, the wen have 0.11.0~ynh2.

Or you could try to install it from a different branch, here "Example". But I don't know the syntax.

**Comment by ericgaspar** [comment]
I am testing the example branch. It seems to fix the issue.

@CodeFreezr  you can try `sudo yunohost app install https://github.com/YunoHost-Apps/excalidraw_ynh/tree/example`
If you have an issue, feel free to provide logs

**Comment by mdic** [comment]
I have tried using the command suggested by @ericgaspar but unfortunately the app is still not working; this time, rather than showing the *Loading scene* message, it goes to a 404.

[Here is the full log of the installation](https://paste.yunohost.org/raw/ceriziyute): I'm not really tech savvy, so I can't evaluate what's happening. Looking at the `/var/www/excalidraw` folder from ssh, it appears that it contains a further folder called `live` where all the files are stored. This path (which I didn't notice in the `master` branch, where all the file were residing inside of the `/var/www/excalidraw` main folder) appears to be correctly set in `/etc/nginx/conf.d/lavagnetta.DOMAIN.LTD.d/excalidraw.conf`:

```
#sub_path_only rewrite ^/$ / permanent;
location / {

  # Path to source
  alias /var/www/excalidraw/live/ ;

  index index.html;

  # Common parameter to increase upload size limit in conjunction with dedicated php-fpm file
  #client_max_body_size 50M;

  try_files $uri $uri/ index.html;

  # Include SSOWAT user panel.
  include conf.d/yunohost_panel.conf.inc;
}
```

any suggestions? Thanks in advance! :)
